extends RefCounted

static func build_item_defs() -> Dictionary:
	return {
		"axe": {
			"name": "Axe Rack",
			"short": "AXE",
			"size": Vector2i(2, 2),
			"color": Color("ffb36b"),
			"description_lines": ["Adds 1 Whirling Axe card", "Card cooldown scales with item level"],
			"tags": ["weapon", "metal", "axe"],
			"stats": {"attack": 5.0},
			"synergy_sockets": [
				{"offset": Vector2i(-1, 0), "tag": "support", "bonuses": {"attack": 2.0, "card_charge_mult": 0.9}},
				{"offset": Vector2i(2, 1), "tag": "metal", "bonuses": {"card_damage": 5.0}},
			],
			"hand_card": {"card_id": "axe_card", "door_interval": 3, "generation_mode": "door_interval", "cooldown_scales_with_item_level": true, "initial_queued_cards": 1, "max_stored_cards": 1},
		},
		"daggers": {
			"name": "Daggers",
			"short": "DAG",
			"size": Vector2i(1, 2),
			"color": Color("d8e4ff"),
			"description_lines": ["Adds 3 Dagger Fan cards", "Card cooldown scales with item level"],
			"tags": ["weapon", "blade", "dagger"],
			"stats": {"attack": 3.0},
			"synergy_sockets": [
				{"offset": Vector2i(1, 0), "tag": "support", "bonuses": {"projectile_count": 1}},
				{"offset": Vector2i(1, 1), "tag": "metal", "bonuses": {"dagger_backstab_bonus": 0.25, "card_charge_mult": 0.92}},
			],
			"hand_card": {"card_id": "dagger_card", "door_interval": 2, "generation_mode": "door_interval", "cooldown_scales_with_item_level": true, "initial_queued_cards": 3, "max_stored_cards": 3},
		},
		"boots": {
			"name": "Boots of Speed",
			"short": "BOS",
			"size": Vector2i(2, 1),
			"color": Color("8ed7c5"),
			"description_lines": ["Move faster", "Adds Speed Dash: target any opened room", "Dash there at 4x speed and keep it for 6s"],
			"tags": ["gear", "footwear"],
			"stats": {"speed": 36.0},
			"synergy_sockets": [
				{"offset": Vector2i(0, -1), "tag": "support", "bonuses": {"speed": 14.0}},
			],
			"hand_card": {"card_id": "speed_dash_card", "door_interval": 1, "generation_mode": "door_interval", "max_stored_cards": 1},
		},
		"whirling_blade": {
			"name": "Whirling Blade",
			"short": "WBL",
			"size": Vector2i(1, 2),
			"color": Color("ffd38a"),
			"description_lines": ["Adds a room-to-room spinning strike", "Hits and knocks back enemies in an AoE sweep"],
			"tags": ["weapon", "blade", "metal"],
			"stats": {"attack": 5.0},
			"synergy_sockets": [
				{"offset": Vector2i(1, 0), "tag": "support", "bonuses": {"card_charge_mult": 0.9}},
			],
			"hand_card": {"card_id": "whirling_blade_card", "door_interval": 2, "generation_mode": "door_interval", "max_stored_cards": 1},
		},
		"ration": {
			"name": "Ration",
			"short": "RAT",
			"size": Vector2i(1, 2),
			"color": Color("c8e07b"),
			"description_lines": ["Packed emergency meal", "Auto-triggers on fatal damage and is consumed"],
			"tags": ["food", "support"],
			"stats": {"health": 12.0, "hand_size": 1},
			"hand_cards": [
				{"card_id": "ration_meal_card", "generation_mode": "single", "consume_item_on_play": true, "max_stored_cards": 1},
			],
			"synergy_sockets": [
				{"offset": Vector2i(0, -1), "tag": "support", "bonuses": {"hand_size": 1}},
			],
		},
		"buckler": {
			"name": "Buckler",
			"short": "BCK",
			"size": Vector2i(2, 2),
			"color": Color("9ec3ff"),
			"description_lines": ["Health buffer", "Adds 2 Shield Bash cards", "Shield Bash knocks back enemies and applies a recovering 6s slow"],
			"tags": ["armor", "metal"],
			"stats": {"health": 18.0},
			"synergy_sockets": [
				{"offset": Vector2i(-1, 1), "tag": "weapon", "bonuses": {"card_charge_mult": 0.92}},
			],
			"hand_card": {"card_id": "shield_bash_card", "door_interval": 2, "generation_mode": "door_interval", "initial_queued_cards": 2, "max_stored_cards": 2},
		},
		"lantern": {
			"name": "Lantern",
			"short": "LNT",
			"size": Vector2i(1, 2),
			"color": Color("ffe38a"),
			"description_lines": ["Three-use utility light", "Readies lamp oil per door, up to one held", "Lamp oil creates one torch in a hero backpack"],
			"tags": ["support", "light"],
			"stats": {"hand_size": 1},
			"max_charges": 3,
			"synergy_sockets": [
				{"offset": Vector2i(1, 0), "tag": "support", "bonuses": {"card_charge_mult": 0.85}},
			],
			"hand_card": {"card_id": "lantern_torch_card", "door_interval": 1, "generation_mode": "door_interval", "max_stored_cards": 1, "consume_item_charges_on_play": 1},
		},
		"medkit": {
			"name": "Medkit",
			"short": "MED",
			"size": Vector2i(2, 1),
			"color": Color("ff9b9b"),
			"description_lines": ["Adds a Mend card immediately", "Mend is a large combat heal"],
			"tags": ["support", "medical"],
			"stats": {"health": 8.0},
			"max_charges": 2,
			"synergy_sockets": [
				{"offset": Vector2i(0, 1), "tag": "food", "bonuses": {"health": 4.0}},
				{"offset": Vector2i(2, 0), "tag": "support", "bonuses": {"card_charge_mult": 0.9}},
			],
			"hand_card": {"card_id": "mend_card", "door_interval": 3, "generation_mode": "door_interval", "max_stored_cards": 1, "consume_item_charges_on_play": 1},
		},
		"torch": {
			"name": "Torch",
			"short": "TOR",
			"size": Vector2i(1, 2),
			"color": Color("ffbf73"),
			"description_lines": ["Single-use utility light", "Consumed when its torch card is played"],
			"tags": ["support", "light", "torch"],
			"hand_card": {"card_id": "torch_card", "generation_mode": "single", "consume_item_on_play": true},
		},
		"spellbook": {
			"name": "Spellbook",
			"short": "SPB",
			"size": Vector2i(1, 2),
			"color": Color("caa8ff"),
			"description_lines": ["Wizard focus", "Slots learned spells for one cast each floor"],
			"tags": ["arcane", "book", "support"],
			"stats": {"hand_size": 1},
		},
		"holy_symbol": {
			"name": "Holy Symbol",
			"short": "HLY",
			"size": Vector2i(1, 1),
			"color": Color("d8e8a8"),
			"description_lines": ["Cleric focus", "Prepares prayers for one cast each floor"],
			"tags": ["divine", "focus", "support"],
			"stats": {"hand_size": 1},
		},
		"scroll_fireball": {
			"name": "Scroll of Fireball",
			"short": "SFB",
			"size": Vector2i(1, 2),
			"color": Color("ff9a5e"),
			"description_lines": ["Single-use spell scroll", "Cast once or study in calm as a wizard"],
			"tags": ["arcane", "scroll"],
			"hand_card": {"card_id": "fireball_card", "generation_mode": "single", "phase_override": "any", "learnable_spell_scroll": true, "consume_item_on_play": true, "max_stored_cards": 1, "name_override": "Fireball Scroll", "description_lines_override": ["Cast Fireball once", "Wizard can study it in calm mode"]},
		},
		"scroll_magic_missile": {
			"name": "Scroll of Magic Missile",
			"short": "SMM",
			"size": Vector2i(1, 2),
			"color": Color("c18dff"),
			"description_lines": ["Single-use spell scroll", "Cast once or study in calm as a wizard"],
			"tags": ["arcane", "scroll"],
			"hand_card": {"card_id": "magic_missile_card", "generation_mode": "single", "phase_override": "any", "learnable_spell_scroll": true, "consume_item_on_play": true, "max_stored_cards": 1, "name_override": "Magic Missile Scroll", "description_lines_override": ["Launch seeking missiles once", "Wizard can study it in calm mode"]},
		},
		"scroll_misty_step": {
			"name": "Scroll of Misty Step",
			"short": "SMS",
			"size": Vector2i(1, 2),
			"color": Color("b89cff"),
			"description_lines": ["Single-use spell scroll", "Cast once or study in calm as a wizard"],
			"tags": ["arcane", "scroll"],
			"hand_card": {"card_id": "misty_step_card", "generation_mode": "single", "phase_override": "any", "learnable_spell_scroll": true, "consume_item_on_play": true, "max_stored_cards": 1, "name_override": "Misty Step Scroll", "description_lines_override": ["Fatal reaction: step one room toward crystal", "Or play on an adjacent room to teleport"]},
		},
		"scroll_web": {
			"name": "Scroll of Web",
			"short": "SWB",
			"size": Vector2i(1, 2),
			"color": Color("c9f0ff"),
			"description_lines": ["Single-use spell scroll", "Cast once or study in calm as a wizard"],
			"tags": ["arcane", "scroll"],
			"hand_card": {"card_id": "web_card", "generation_mode": "single", "phase_override": "any", "learnable_spell_scroll": true, "consume_item_on_play": true, "max_stored_cards": 1, "name_override": "Web Scroll", "description_lines_override": ["Root enemies in an area once", "Wizard can study it in calm mode"]},
		},
		"scroll_shield": {
			"name": "Scroll of Shield",
			"short": "SSH",
			"size": Vector2i(1, 2),
			"color": Color("9fc8ff"),
			"description_lines": ["Single-use spell scroll", "Cast once or study in calm as a wizard"],
			"tags": ["arcane", "scroll"],
			"hand_card": {"card_id": "shield_card", "generation_mode": "single", "phase_override": "any", "learnable_spell_scroll": true, "consume_item_on_play": true, "max_stored_cards": 1, "name_override": "Shield Scroll", "description_lines_override": ["Gain a temporary arcane barrier", "Wizard can study it in calm mode"]},
		},
		"scroll_scorching_ray": {
			"name": "Scroll of Animate Dead",
			"short": "SAD",
			"size": Vector2i(1, 2),
			"color": Color("d9f4e2"),
			"description_lines": ["Single-use spell scroll", "Wizard can study in calm; cleric can prepare when level allows"],
			"tags": ["arcane", "scroll", "necromancy"],
			"hand_card": {"card_id": "summon_warden_spirit_card", "generation_mode": "single", "phase_override": "any", "learnable_spell_scroll": true, "consume_item_on_play": true, "max_stored_cards": 1, "name_override": "Animate Dead Scroll", "description_lines_override": ["Summon greatsword, armored, and skeleton allies", "Cleric prepares by level; wizard can study in calm mode"]},
		},
		"scroll_lightning_bolt": {
			"name": "Scroll of Lightning Bolt",
			"short": "SLB",
			"size": Vector2i(1, 2),
			"color": Color("8bd9ff"),
			"description_lines": ["Single-use spell scroll", "Cast once or study in calm as a wizard"],
			"tags": ["arcane", "scroll"],
			"hand_card": {"card_id": "lightning_bolt_card", "generation_mode": "single", "phase_override": "any", "learnable_spell_scroll": true, "consume_item_on_play": true, "max_stored_cards": 1, "name_override": "Lightning Bolt Scroll", "description_lines_override": ["Fire a piercing line through a doorway", "Wizard can study it in calm mode"]},
		},
		"scroll_light_cantrip": {
			"name": "Scroll of Light",
			"short": "SLT",
			"size": Vector2i(1, 2),
			"color": Color("fff1a8"),
			"description_lines": ["Single-use spell scroll", "Cast once or study in calm as a wizard"],
			"tags": ["arcane", "scroll"],
			"hand_card": {"card_id": "light_cantrip_card", "generation_mode": "single", "phase_override": "any", "learnable_spell_scroll": true, "consume_item_on_play": true, "max_stored_cards": 1, "name_override": "Light Scroll", "description_lines_override": ["Create wizard light once", "Wizard can study it in calm mode"]},
		},
		"scroll_scry": {
			"name": "Scroll of Scry",
			"short": "SCR",
			"size": Vector2i(1, 2),
			"color": Color("9ed7ff"),
			"description_lines": ["Single-use spell scroll", "Cast once or study in calm as a wizard"],
			"tags": ["arcane", "scroll"],
			"hand_card": {"card_id": "scry_card", "generation_mode": "single", "phase_override": "any", "learnable_spell_scroll": true, "consume_item_on_play": true, "max_stored_cards": 1, "name_override": "Scry Scroll", "description_lines_override": ["Reveal adjacent sealed rooms once", "Wizard can study it in calm mode"]},
		},
		"scroll_summon_arcane_sentinel": {
			"name": "Scroll of Find Familiar",
			"short": "SFF",
			"size": Vector2i(1, 2),
			"color": Color("b8d1ff"),
			"description_lines": ["Single-use spell scroll", "Cast once or study in calm as a wizard"],
			"tags": ["arcane", "scroll"],
			"hand_card": {"card_id": "summon_arcane_sentinel_card", "generation_mode": "single", "phase_override": "any", "learnable_spell_scroll": true, "consume_item_on_play": true, "max_stored_cards": 1, "name_override": "Find Familiar Scroll", "description_lines_override": ["Summon an allied familiar once", "Wizard can study it in calm mode"]},
		},
		"scroll_cure_light_wounds": {
			"name": "Scroll of Cure Light Wounds",
			"short": "SCW",
			"size": Vector2i(1, 2),
			"color": Color("c3ffb3"),
			"description_lines": ["Single-use prayer scroll", "Cast once or study in calm as a cleric"],
			"tags": ["divine", "scroll"],
			"hand_card": {"card_id": "cure_light_wounds_card", "generation_mode": "single", "phase_override": "any", "learnable_spell_scroll": true, "consume_item_on_play": true, "max_stored_cards": 1, "name_override": "Cure Light Wounds Scroll", "description_lines_override": ["Restore 50% max health once", "Auto-casts to save a fallen ally in the same room"]},
		},
		"scroll_sanctuary": {
			"name": "Scroll of Sanctuary",
			"short": "SSY",
			"size": Vector2i(1, 2),
			"color": Color("e3ff9f"),
			"description_lines": ["Single-use prayer scroll", "Cast once or study in calm as a cleric"],
			"tags": ["divine", "scroll"],
			"hand_card": {"card_id": "sanctuary_card", "generation_mode": "single", "phase_override": "any", "learnable_spell_scroll": true, "consume_item_on_play": true, "max_stored_cards": 1, "name_override": "Sanctuary Scroll", "description_lines_override": ["Bless one room once", "Cleric can study it in calm mode"]},
		},
		"scroll_hold_person": {
			"name": "Scroll of Hold Person",
			"short": "SHP",
			"size": Vector2i(1, 2),
			"color": Color("d9c0ff"),
			"description_lines": ["Single-use prayer scroll", "Cast once or study in calm as a cleric"],
			"tags": ["divine", "scroll"],
			"hand_card": {"card_id": "hold_person_card", "generation_mode": "single", "phase_override": "any", "learnable_spell_scroll": true, "consume_item_on_play": true, "max_stored_cards": 1, "name_override": "Hold Person Scroll", "description_lines_override": ["Paralyze one enemy once", "Melee attacks against that target are critical"]},
		},
		"scroll_fear": {
			"name": "Scroll of Fear",
			"short": "SFR",
			"size": Vector2i(1, 2),
			"color": Color("cda3ff"),
			"description_lines": ["Single-use prayer scroll", "Cast once or study in calm as a cleric"],
			"tags": ["divine", "scroll"],
			"hand_card": {"card_id": "fear_card", "generation_mode": "single", "phase_override": "any", "learnable_spell_scroll": true, "consume_item_on_play": true, "max_stored_cards": 1, "name_override": "Fear Scroll", "description_lines_override": ["Terrify enemies in a long cone for 6s", "Feared enemies flee and take 2x damage"]},
		},
		"scroll_spiritual_weapon": {
			"name": "Scroll of Spiritual Weapon",
			"short": "SSW",
			"size": Vector2i(1, 2),
			"color": Color("f0f1ff"),
			"description_lines": ["Single-use prayer scroll", "Cast once; clerics auto-prepare this prayer by level"],
			"tags": ["divine", "scroll"],
			"hand_card": {"card_id": "spiritual_weapon_card", "generation_mode": "single", "phase_override": "any", "learnable_spell_scroll": true, "consume_item_on_play": true, "max_stored_cards": 1, "name_override": "Spiritual Weapon Scroll", "description_lines_override": ["Summon an invulnerable spectral blade once", "No study required for clerics"]},
		},
		"scroll_summon_warden_spirit": {
			"name": "Scroll of Animate Dead",
			"short": "SWS",
			"size": Vector2i(1, 2),
			"color": Color("d0ffbe"),
			"description_lines": ["Single-use prayer scroll", "Cast once or study in calm as a cleric"],
			"tags": ["divine", "scroll"],
			"hand_card": {"card_id": "summon_warden_spirit_card", "generation_mode": "single", "phase_override": "any", "learnable_spell_scroll": true, "consume_item_on_play": true, "max_stored_cards": 1, "name_override": "Animate Dead Scroll", "description_lines_override": ["Summon greatsword, armored, and skeleton allies", "Cleric prepares by level; wizard can study in calm mode"]},
		},
	}
