extends RefCounted

static func build_item_defs() -> Dictionary:
	return {
		"axe": {
			"name": "Axe Rack",
			"short": "AXE",
			"size": Vector2i(2, 2),
			"color": Color("ffb36b"),
			"description_lines": ["Passive: hurls a bouncing axe in combat", "Synergies boost proc speed and damage"],
			"tags": ["weapon", "metal", "axe"],
			"stats": {"attack": 5.0},
			"synergy_sockets": [
				{"offset": Vector2i(-1, 0), "tag": "support", "bonuses": {"attack": 2.0, "card_charge_mult": 0.9}},
				{"offset": Vector2i(2, 1), "tag": "metal", "bonuses": {"card_damage": 5.0}},
			],
			"passive_combat_ability": {"card_id": "axe_card", "cooldown": 1.8},
		},
		"daggers": {
			"name": "Daggers",
			"short": "DAG",
			"size": Vector2i(1, 2),
			"color": Color("d8e4ff"),
			"description_lines": ["Passive: fires a 3-dagger fan in combat", "Back hits build combo and bonus damage"],
			"tags": ["weapon", "blade", "dagger"],
			"stats": {"attack": 3.0},
			"synergy_sockets": [
				{"offset": Vector2i(1, 0), "tag": "support", "bonuses": {"projectile_count": 1}},
				{"offset": Vector2i(1, 1), "tag": "metal", "bonuses": {"dagger_backstab_bonus": 0.25, "card_charge_mult": 0.92}},
			],
			"passive_combat_ability": {"card_id": "dagger_card", "cooldown": 1.35},
		},
		"blade": {
			"name": "Blade",
			"short": "BLD",
			"size": Vector2i(1, 2),
			"color": Color("ffb36b"),
			"description_lines": ["Simple weapon upgrade", "Purely boosts attack"],
			"tags": ["weapon", "metal"],
			"stats": {"attack": 6.0},
			"synergy_sockets": [
				{"offset": Vector2i(1, 0), "tag": "tool", "bonuses": {"attack": 2.0}},
			],
		},
		"boots": {
			"name": "Boots",
			"short": "BOT",
			"size": Vector2i(2, 1),
			"color": Color("8ed7c5"),
			"description_lines": ["Move faster and gain stamina", "Pairs well with support gear"],
			"tags": ["gear", "footwear"],
			"stats": {"speed": 36.0, "stamina": 1.0},
			"synergy_sockets": [
				{"offset": Vector2i(0, -1), "tag": "support", "bonuses": {"stamina": 1.0}},
			],
		},
		"ration": {
			"name": "Ration",
			"short": "RAT",
			"size": Vector2i(1, 2),
			"color": Color("c8e07b"),
			"description_lines": ["Packed meals for recovery", "Adds a self-support card over dungeon turns"],
			"tags": ["food", "support"],
			"stats": {"health": 12.0, "hand_size": 1},
			"hand_cards": [
				{"card_id": "ration_meal_card", "door_interval": 2, "generation_mode": "door_interval", "max_stored_cards": 1},
			],
			"synergy_sockets": [
				{"offset": Vector2i(0, -1), "tag": "support", "bonuses": {"hand_size": 1}},
			],
		},
		"buckler": {
			"name": "Buckler",
			"short": "BCK",
			"size": Vector2i(2, 2),
			"color": Color("9ec3ff"),
			"description_lines": ["Health and stamina buffer", "Weapon synergy lowers card stamina cost"],
			"tags": ["armor", "metal"],
			"stats": {"health": 18.0, "stamina": 1.0},
			"synergy_sockets": [
				{"offset": Vector2i(-1, 1), "tag": "weapon", "bonuses": {"stamina_cost_mult": 0.92}},
			],
		},
		"whetstone": {
			"name": "Whetstone",
			"short": "WHT",
			"size": Vector2i(1, 1),
			"color": Color("f2e4a4"),
			"description_lines": ["Star tool", "Stars buff neighboring weapons"],
			"tags": ["tool"],
			"synergy_sockets": [
				{"offset": Vector2i(-1, 0), "tag": "weapon", "bonuses": {"attack": 4.0}},
				{"offset": Vector2i(1, 0), "tag": "weapon", "bonuses": {"attack": 4.0}},
				{"offset": Vector2i(0, -1), "tag": "weapon", "bonuses": {"attack": 4.0}},
				{"offset": Vector2i(0, 1), "tag": "weapon", "bonuses": {"attack": 4.0}},
			],
		},
		"banner": {
			"name": "Banner",
			"short": "BNR",
			"size": Vector2i(1, 3),
			"color": Color("ea7e7e"),
			"description_lines": ["Star support standard", "Perimeter stars aid armor and weapons"],
			"tags": ["support"],
			"synergy_sockets": [
				{"offset": Vector2i(-1, 0), "matches": [{"tag": "armor", "bonuses": {"health": 8.0}}, {"tag": "weapon", "bonuses": {"attack": 2.0}}]},
				{"offset": Vector2i(-1, 1), "matches": [{"tag": "armor", "bonuses": {"health": 8.0}}, {"tag": "weapon", "bonuses": {"attack": 2.0}}]},
				{"offset": Vector2i(-1, 2), "matches": [{"tag": "armor", "bonuses": {"health": 8.0}}, {"tag": "weapon", "bonuses": {"attack": 2.0}}]},
				{"offset": Vector2i(1, 0), "matches": [{"tag": "armor", "bonuses": {"health": 8.0}}, {"tag": "weapon", "bonuses": {"attack": 2.0}}]},
				{"offset": Vector2i(1, 1), "matches": [{"tag": "armor", "bonuses": {"health": 8.0}}, {"tag": "weapon", "bonuses": {"attack": 2.0}}]},
				{"offset": Vector2i(1, 2), "matches": [{"tag": "armor", "bonuses": {"health": 8.0}}, {"tag": "weapon", "bonuses": {"attack": 2.0}}]},
				{"offset": Vector2i(0, -1), "matches": [{"tag": "armor", "bonuses": {"health": 8.0}}, {"tag": "weapon", "bonuses": {"attack": 2.0}}]},
				{"offset": Vector2i(0, 3), "matches": [{"tag": "armor", "bonuses": {"health": 8.0}}, {"tag": "weapon", "bonuses": {"attack": 2.0}}]},
			],
		},
		"lantern": {
			"name": "Lantern",
			"short": "LNT",
			"size": Vector2i(1, 2),
			"color": Color("ffe38a"),
			"description_lines": ["Three-use utility light", "Readies one torch card per door, up to one held"],
			"tags": ["support", "light"],
			"stats": {"hand_size": 1},
			"max_charges": 3,
			"synergy_sockets": [
				{"offset": Vector2i(1, 0), "tag": "support", "bonuses": {"card_charge_mult": 0.85}},
			],
			"hand_card": {"card_id": "torch_card", "door_interval": 1, "generation_mode": "door_interval", "max_stored_cards": 1, "consume_item_charges_on_play": 1},
		},
		"medkit": {
			"name": "Medkit",
			"short": "MED",
			"size": Vector2i(2, 1),
			"color": Color("ff9b9b"),
			"description_lines": ["Adds a Mend card immediately", "Mend is a large combat heal"],
			"tags": ["support", "medical"],
			"stats": {"health": 8.0},
			"max_charges": 2,
			"synergy_sockets": [
				{"offset": Vector2i(0, 1), "tag": "food", "bonuses": {"health": 4.0}},
				{"offset": Vector2i(2, 0), "tag": "support", "bonuses": {"card_charge_mult": 0.9}},
			],
			"hand_card": {"card_id": "mend_card", "door_interval": 3, "generation_mode": "door_interval", "max_stored_cards": 1, "consume_item_charges_on_play": 1},
		},
		"torch": {
			"name": "Torch",
			"short": "TOR",
			"size": Vector2i(1, 2),
			"color": Color("ffbf73"),
			"description_lines": ["Single-use utility light", "Consumed when its torch card is played"],
			"tags": ["support", "light", "torch"],
			"hand_card": {"card_id": "torch_card", "generation_mode": "single", "consume_item_on_play": true},
		},
		"spellbook": {
			"name": "Spellbook",
			"short": "SPB",
			"size": Vector2i(1, 2),
			"color": Color("caa8ff"),
			"description_lines": ["Wizard focus", "Slots learned spells for one cast each floor"],
			"tags": ["arcane", "book", "support"],
			"stats": {"hand_size": 1},
		},
		"holy_symbol": {
			"name": "Holy Symbol",
			"short": "HLY",
			"size": Vector2i(1, 1),
			"color": Color("d8e8a8"),
			"description_lines": ["Cleric focus", "Prepares prayers for one cast each floor"],
			"tags": ["divine", "focus", "support"],
			"stats": {"hand_size": 1},
		},
		"scroll_fireball": {
			"name": "Scroll of Fireball",
			"short": "SFB",
			"size": Vector2i(1, 2),
			"color": Color("ff9a5e"),
			"description_lines": ["Single-use spell scroll", "Cast once or study in calm as a wizard"],
			"tags": ["arcane", "scroll"],
			"hand_card": {"card_id": "fireball_card", "generation_mode": "single", "phase_override": "any", "learnable_spell_scroll": true, "consume_item_on_play": true, "max_stored_cards": 1, "name_override": "Fireball Scroll", "description_lines_override": ["Cast Fireball once", "Wizard can study it in calm mode"]},
		},
		"scroll_magic_missile": {
			"name": "Scroll of Magic Missile",
			"short": "SMM",
			"size": Vector2i(1, 2),
			"color": Color("c18dff"),
			"description_lines": ["Single-use spell scroll", "Cast once or study in calm as a wizard"],
			"tags": ["arcane", "scroll"],
			"hand_card": {"card_id": "magic_missile_card", "generation_mode": "single", "phase_override": "any", "learnable_spell_scroll": true, "consume_item_on_play": true, "max_stored_cards": 1, "name_override": "Magic Missile Scroll", "description_lines_override": ["Launch seeking missiles once", "Wizard can study it in calm mode"]},
		},
		"scroll_misty_step": {
			"name": "Scroll of Misty Step",
			"short": "SMS",
			"size": Vector2i(1, 2),
			"color": Color("b89cff"),
			"description_lines": ["Single-use spell scroll", "Cast once or study in calm as a wizard"],
			"tags": ["arcane", "scroll"],
			"hand_card": {"card_id": "misty_step_card", "generation_mode": "single", "phase_override": "any", "learnable_spell_scroll": true, "consume_item_on_play": true, "max_stored_cards": 1, "name_override": "Misty Step Scroll", "description_lines_override": ["Teleport once to a seen room", "Wizard can study it in calm mode"]},
		},
		"scroll_web": {
			"name": "Scroll of Web",
			"short": "SWB",
			"size": Vector2i(1, 2),
			"color": Color("c9f0ff"),
			"description_lines": ["Single-use spell scroll", "Cast once or study in calm as a wizard"],
			"tags": ["arcane", "scroll"],
			"hand_card": {"card_id": "web_card", "generation_mode": "single", "phase_override": "any", "learnable_spell_scroll": true, "consume_item_on_play": true, "max_stored_cards": 1, "name_override": "Web Scroll", "description_lines_override": ["Root enemies in an area once", "Wizard can study it in calm mode"]},
		},
		"scroll_shield": {
			"name": "Scroll of Shield",
			"short": "SSH",
			"size": Vector2i(1, 2),
			"color": Color("9fc8ff"),
			"description_lines": ["Single-use spell scroll", "Cast once or study in calm as a wizard"],
			"tags": ["arcane", "scroll"],
			"hand_card": {"card_id": "shield_card", "generation_mode": "single", "phase_override": "any", "learnable_spell_scroll": true, "consume_item_on_play": true, "max_stored_cards": 1, "name_override": "Shield Scroll", "description_lines_override": ["Gain a temporary arcane barrier", "Wizard can study it in calm mode"]},
		},
		"scroll_scorching_ray": {
			"name": "Scroll of Scorching Ray",
			"short": "SSR",
			"size": Vector2i(1, 2),
			"color": Color("ffb366"),
			"description_lines": ["Single-use spell scroll", "Cast once or study in calm as a wizard"],
			"tags": ["arcane", "scroll"],
			"hand_card": {"card_id": "scorching_ray_card", "generation_mode": "single", "phase_override": "any", "learnable_spell_scroll": true, "consume_item_on_play": true, "max_stored_cards": 1, "name_override": "Scorching Ray Scroll", "description_lines_override": ["Fire three scorching rays once", "Wizard can study it in calm mode"]},
		},
		"scroll_lightning_bolt": {
			"name": "Scroll of Lightning Bolt",
			"short": "SLB",
			"size": Vector2i(1, 2),
			"color": Color("8bd9ff"),
			"description_lines": ["Single-use spell scroll", "Cast once or study in calm as a wizard"],
			"tags": ["arcane", "scroll"],
			"hand_card": {"card_id": "lightning_bolt_card", "generation_mode": "single", "phase_override": "any", "learnable_spell_scroll": true, "consume_item_on_play": true, "max_stored_cards": 1, "name_override": "Lightning Bolt Scroll", "description_lines_override": ["Fire a piercing line through a doorway", "Wizard can study it in calm mode"]},
		},
	}
