extends RefCounted

const TARGET_CATEGORY_RANGED: String = "ranged_target"
const TARGET_CATEGORY_MELEE: String = "melee_target"
const TARGET_CATEGORY_RESEARCH_CRYSTAL: String = "research_crystal"
const TARGET_CATEGORY_MAJOR_MODULE: String = "major_module"
const TARGET_CATEGORY_MINOR_MODULE: String = "minor_module"
const TARGET_CATEGORY_GENERATOR_CRYSTAL: String = "generator_crystal"

const DEFAULT_PRIORITY_TABLE: Dictionary = {
	TARGET_CATEGORY_MELEE: 1,
	TARGET_CATEGORY_RANGED: 2,
	TARGET_CATEGORY_RESEARCH_CRYSTAL: 3,
	TARGET_CATEGORY_MAJOR_MODULE: -1,
	TARGET_CATEGORY_MINOR_MODULE: -1,
	TARGET_CATEGORY_GENERATOR_CRYSTAL: 5,
}

# Lower number = higher priority. Negative priority disables a category for that role.
const ROLE_PRIORITY_TABLE: Dictionary = {
	"orc": {
		TARGET_CATEGORY_MELEE: 1,
		TARGET_CATEGORY_RANGED: 2,
		TARGET_CATEGORY_RESEARCH_CRYSTAL: 3,
		TARGET_CATEGORY_MAJOR_MODULE: -1,
		TARGET_CATEGORY_GENERATOR_CRYSTAL: 5,
	},
	"orc_rider": {
		TARGET_CATEGORY_MELEE: 1,
		TARGET_CATEGORY_RANGED: 2,
		TARGET_CATEGORY_RESEARCH_CRYSTAL: 3,
		TARGET_CATEGORY_MAJOR_MODULE: -1,
		TARGET_CATEGORY_GENERATOR_CRYSTAL: 5,
	},
	"death_knight": {
		TARGET_CATEGORY_MELEE: 1,
		TARGET_CATEGORY_RANGED: 2,
		TARGET_CATEGORY_RESEARCH_CRYSTAL: 3,
		TARGET_CATEGORY_MAJOR_MODULE: -1,
		TARGET_CATEGORY_GENERATOR_CRYSTAL: 5,
	},
	"skeleton_archer": {
		TARGET_CATEGORY_RANGED: 1,
		TARGET_CATEGORY_MELEE: 2,
		TARGET_CATEGORY_RESEARCH_CRYSTAL: 3,
		TARGET_CATEGORY_MAJOR_MODULE: -1,
		TARGET_CATEGORY_GENERATOR_CRYSTAL: 5,
	},
	"hellhound": {
		TARGET_CATEGORY_MELEE: 1,
		TARGET_CATEGORY_RANGED: 2,
		TARGET_CATEGORY_RESEARCH_CRYSTAL: 3,
		TARGET_CATEGORY_MAJOR_MODULE: 4,
		TARGET_CATEGORY_GENERATOR_CRYSTAL: 5,
	},
	"slime": {
		TARGET_CATEGORY_MELEE: 1,
		TARGET_CATEGORY_RANGED: 2,
		TARGET_CATEGORY_RESEARCH_CRYSTAL: -1,
		TARGET_CATEGORY_MAJOR_MODULE: -1,
		TARGET_CATEGORY_MINOR_MODULE: 3,
		TARGET_CATEGORY_GENERATOR_CRYSTAL: -1,
	},
	"archer_imp": {
		TARGET_CATEGORY_RANGED: 1,
		TARGET_CATEGORY_MELEE: 2,
		TARGET_CATEGORY_RESEARCH_CRYSTAL: 3,
		TARGET_CATEGORY_MAJOR_MODULE: -1,
		TARGET_CATEGORY_GENERATOR_CRYSTAL: 5,
	},
	"wraith": {
		TARGET_CATEGORY_RANGED: 1,
		TARGET_CATEGORY_MELEE: 2,
		TARGET_CATEGORY_RESEARCH_CRYSTAL: 3,
		TARGET_CATEGORY_MAJOR_MODULE: -1,
		TARGET_CATEGORY_GENERATOR_CRYSTAL: 5,
	},
	"bat": {
		TARGET_CATEGORY_RESEARCH_CRYSTAL: 1,
		TARGET_CATEGORY_MAJOR_MODULE: -1,
		TARGET_CATEGORY_GENERATOR_CRYSTAL: 3,
		TARGET_CATEGORY_MELEE: -1,
		TARGET_CATEGORY_RANGED: -1,
	},
	"golem": {
		TARGET_CATEGORY_RESEARCH_CRYSTAL: 1,
		TARGET_CATEGORY_MAJOR_MODULE: -1,
		TARGET_CATEGORY_GENERATOR_CRYSTAL: 3,
		TARGET_CATEGORY_MELEE: -1,
		TARGET_CATEGORY_RANGED: -1,
	},
	"demon_d": {
		TARGET_CATEGORY_RESEARCH_CRYSTAL: 1,
		TARGET_CATEGORY_MAJOR_MODULE: -1,
		TARGET_CATEGORY_GENERATOR_CRYSTAL: 3,
		TARGET_CATEGORY_MELEE: -1,
		TARGET_CATEGORY_RANGED: -1,
	},
}

static func priority_table_for_role(enemy_role: String) -> Dictionary:
	var table: Dictionary = Dictionary(DEFAULT_PRIORITY_TABLE).duplicate(true)
	var role_table: Dictionary = Dictionary(ROLE_PRIORITY_TABLE.get(enemy_role, {}))
	for category in role_table.keys():
		table[category] = role_table[category]
	return table
