extends RefCounted

static func build_item_defs() -> Dictionary:
	var definitions: Dictionary = {
		"axe": {
			"name": "Razor Boomerang",
			"short": "RBM",
			"size": Vector2i(2, 2),
			"footprint_cells": [Vector2i(0, 0), Vector2i(0, 1), Vector2i(1, 1)],
			"color": Color("ffb36b"),
			"description_lines": ["Adds 2 Razor Boomerang cards", "L-shaped footprint", "Card cooldown scales with item level"],
			"tags": ["weapon", "physical"],
			"synergy_sockets": [
				{"offset": Vector2i(0, 2), "tag": "poison", "bonuses": {"attack": 6.0}},
			],
			"hand_card": {"card_id": "axe_card", "door_interval": 3, "generation_mode": "door_interval", "cooldown_scales_with_item_level": true, "initial_queued_cards": 2, "max_stored_cards": 2},
		},
		"daggers": {
			"name": "Daggers",
			"short": "DAG",
			"item_level": 1,
			"size": Vector2i(1, 2),
			"color": Color("d8e4ff"),
			"description_lines": ["Adds 3 Dagger Fan cards", "Card cooldown scales with item level"],
			"tags": ["weapon", "physical"],
			"synergy_sockets": [
				{"offset": Vector2i(0, -1), "tag": "poison", "bonuses": {"attack": 5.0}},
			],
			"hand_card": {"card_id": "dagger_card", "door_interval": 2, "generation_mode": "door_interval", "cooldown_scales_with_item_level": true, "initial_queued_cards": 3, "max_stored_cards": 3},
		},
		"ricochet_dagger": {
			"name": "Ricochet Chakram",
			"short": "CHK",
			"item_level": 2,
			"size": Vector2i(3, 3),
			"footprint_cells": [Vector2i(1, 0), Vector2i(0, 1), Vector2i(1, 1), Vector2i(2, 1), Vector2i(1, 2)],
			"color": Color("ffd7a6"),
			"description_lines": ["Level 2 chakram", "Cross-shaped footprint", "Adds 1 Ricochet Chakram card", "If it bounces 3 times before a hit, it explodes like Fireball", "At Combo 3: all enemies damaged by it become Flatfooted"],
			"tags": ["weapon", "physical"],
			"synergy_sockets": [
				{"offset": Vector2i(0, -1), "tag": "poison", "bonuses": {"attack": 8.0}},
			],
			"hand_card": {"card_id": "ricochet_dagger_card", "door_interval": 3, "generation_mode": "door_interval", "cooldown_scales_with_item_level": true, "initial_queued_cards": 1, "max_stored_cards": 1},
		},
		"rogue_bandolier": {
			"name": "Rogue Bandolier",
			"short": "RBL",
			"item_level": 0,
			"size": Vector2i(2, 1),
			"color": Color("a8cfff"),
			"description_lines": ["Starter rogue signature", "Level 0: unlimited uses", "Adds 1 combo dagger card", "Only works at Combo Level 3+"],
			"tags": ["weapon", "physical"],
			"synergy_sockets": [
				{"offset": Vector2i(0, 1), "tag": "poison", "bonuses": {"attack": 4.0}},
			],
			"hand_card": {
				"card_id": "rogue_combo_dagger_card",
				"generation_mode": "single",
				"initial_queued_cards": 1,
				"max_stored_cards": 1,
			},
		},
		"cloak_of_shadows": {
			"name": "Cloak of Shadows",
			"short": "CLS",
			"item_level": 1,
			"size": Vector2i(1, 2),
			"color": Color("9db9ff"),
			"description_lines": ["Level 1 utility cloak", "Adds Cloak of Shadows", "Gain Skulker for 1 dungeon turn", "Scroll star: +defence"],
			"tags": ["magical"],
			"synergy_sockets": [
				{"offset": Vector2i(1, 0), "tag": "scroll", "bonuses": {"defence": 5.0}},
			],
			"hand_card": {"card_id": "cloak_of_shadows_card", "door_interval": 2, "generation_mode": "door_interval", "cooldown_scales_with_item_level": true, "initial_queued_cards": 1, "max_stored_cards": 1},
		},
		"emergency_snack": {
			"name": "Emergency Snack",
			"short": "SNK",
			"item_level": 0,
			"size": Vector2i(1, 1),
			"color": Color("ffd79c"),
			"description_lines": ["Starter snack", "Level 0: unlimited uses", "Adds Emergency Snack"],
			"tags": ["food"],
			"hand_card": {
				"card_id": "emergency_snack_card",
				"door_interval": 1,
				"generation_mode": "door_interval",
				"initial_queued_cards": 1,
				"max_stored_cards": 1,
			},
		},
		"serpent_venom": {
			"name": "Serpent Venom",
			"short": "SVM",
			"size": Vector2i(1, 2),
			"color": Color("8fe78f"),
			"description_lines": ["Single-use coating", "Applies to all physical hits for 1 dungeon turn", "On hit: venom DoT"],
			"tags": ["poison"],
			"max_charges": 1,
			"hand_card": {"card_id": "serpent_venom_card", "door_interval": 1, "generation_mode": "door_interval", "max_stored_cards": 1, "consume_item_charges_on_play": 1},
		},
		"wyvern_toxin": {
			"name": "Wyvern Toxin",
			"short": "WTX",
			"size": Vector2i(1, 2),
			"color": Color("7ad8ff"),
			"description_lines": ["Single-use coating", "Applies to all physical hits for 1 dungeon turn", "On hit: bonus damage and strong slow"],
			"tags": ["poison"],
			"max_charges": 1,
			"hand_card": {"card_id": "wyvern_toxin_card", "door_interval": 1, "generation_mode": "door_interval", "max_stored_cards": 1, "consume_item_charges_on_play": 1},
		},
		"blacklotus_oil": {
			"name": "Black Lotus Oil",
			"short": "BLO",
			"size": Vector2i(1, 2),
			"color": Color("cfb7ff"),
			"description_lines": ["Single-use coating", "Applies to all physical hits for 1 dungeon turn", "On hit: burst flatfooted"],
			"tags": ["poison"],
			"max_charges": 1,
			"hand_card": {"card_id": "blacklotus_oil_card", "door_interval": 1, "generation_mode": "door_interval", "max_stored_cards": 1, "consume_item_charges_on_play": 1},
		},
		"boots": {
			"name": "Boots of Speed",
			"short": "BOS",
			"size": Vector2i(2, 1),
			"color": Color("8ed7c5"),
			"description_lines": ["Adds Speed Dash: target any opened room", "Dash there at 4x speed and keep it for 6s", "Food star socket grants movement speed"],
			"tags": ["physical"],
			"synergy_sockets": [
				{"offset": Vector2i(2, 0), "tag": "food", "bonuses": {"speed": 20.0}},
			],
			"hand_card": {"card_id": "speed_dash_card", "door_interval": 1, "generation_mode": "door_interval", "max_stored_cards": 1},
		},
		"whirling_blade": {
			"name": "Whirling Blade",
			"short": "WBL",
			"size": Vector2i(1, 2),
			"color": Color("ffd38a"),
			"description_lines": ["Adds a room-to-room spinning strike", "Hits and knocks back enemies in an AoE sweep"],
			"tags": ["weapon", "physical"],
			"synergy_sockets": [
				{"offset": Vector2i(0, 2), "tag": "poison", "bonuses": {"attack": 6.0}},
			],
			"hand_card": {"card_id": "whirling_blade_card", "door_interval": 2, "generation_mode": "door_interval", "max_stored_cards": 1},
		},
		"sunpepper_jerky": {
			"name": "Sunpepper Jerky",
			"short": "SPJ",
			"size": Vector2i(2, 2),
			"footprint_cells": [Vector2i(0, 1), Vector2i(1, 0), Vector2i(1, 1)],
			"color": Color("ffb07a"),
			"description_lines": ["Exotic combat ration", "Banana-shaped footprint", "Auto-triggers on fatal damage", "Restore health and boost attack speed"],
			"tags": ["food"],
			"hand_cards": [
				{"card_id": "sunpepper_jerky_card", "generation_mode": "single", "consume_item_on_play": true, "max_stored_cards": 1},
			],
		},
		"moon_truffle": {
			"name": "Moon Truffle",
			"short": "MTR",
			"size": Vector2i(1, 1),
			"color": Color("d8c6ff"),
			"description_lines": ["Silvery deep-cavern delicacy", "1x1 ration", "Auto-triggers on fatal damage", "Restore health and boost defence"],
			"tags": ["food"],
			"hand_cards": [
				{"card_id": "moon_truffle_card", "generation_mode": "single", "consume_item_on_play": true, "max_stored_cards": 1},
			],
		},
		"tidekelp_roll": {
			"name": "Tidekelp Roll",
			"short": "TKR",
			"size": Vector2i(1, 2),
			"color": Color("84d9d1"),
			"description_lines": ["Cold-brined abyssal seaweed", "1x2 ration", "Auto-triggers on fatal damage", "Restore health and boost movement speed"],
			"tags": ["food"],
			"hand_cards": [
				{"card_id": "tidekelp_roll_card", "generation_mode": "single", "consume_item_on_play": true, "max_stored_cards": 1},
			],
		},
		"buckler": {
			"name": "Buckler",
			"short": "BCK",
			"size": Vector2i(2, 2),
			"color": Color("9ec3ff"),
			"description_lines": ["Adds 2 Shield Bash cards", "Shield Bash knocks back enemies and applies a recovering 6s slow"],
			"tags": ["physical"],
			"synergy_sockets": [
				{"offset": Vector2i(-1, 1), "tag": "physical", "bonuses": {"basic_attack_knockback": 180.0}},
			],
			"hand_card": {"card_id": "shield_bash_card", "door_interval": 2, "generation_mode": "door_interval", "initial_queued_cards": 2, "max_stored_cards": 2},
		},
		"silver_gauntlets": {
			"name": "Silver Gauntlets",
			"short": "SG",
			"item_level": 0,
			"size": Vector2i(1, 2),
			"color": Color("c5d4df"),
			"description_lines": ["Fighter starter relic", "Adds Thrash Around", "Consumes all Rage to prime 6 Thrash Around hits", "Each hit throws enemies with Rage-scaled force", "Wall bounces apply Flatfooted (no damage)"],
			"tags": ["weapon", "physical"],
			"hand_card": {
				"card_id": "silver_gauntlet_toss_card",
				"generation_mode": "single",
				"initial_queued_cards": 1,
				"max_stored_cards": 1,
			},
		},
		"lantern": {
			"name": "Lantern",
			"short": "LNT",
			"size": Vector2i(1, 2),
			"color": Color("ffe38a"),
			"description_lines": ["Reusable utility light", "Readies beacon oil per door, up to one held", "Beacon oil lights one opened room for the next wave"],
			"tags": ["magical"],
			"synergy_sockets": [
				{"offset": Vector2i(0, -1), "tag": "food", "bonuses": {"hand_size": 1}},
			],
			"hand_card": {"card_id": "lantern_beacon_card", "door_interval": 1, "generation_mode": "door_interval", "max_stored_cards": 1},
		},
		"spellbook": {
			"name": "Spellbook",
			"short": "SPB",
			"size": Vector2i(1, 2),
			"color": Color("caa8ff"),
			"description_lines": ["Wizard focus", "Slots learned spells for one cast each floor"],
			"tags": ["magical"],
		},
		"holy_symbol": {
			"name": "Holy Symbol",
			"short": "HLY",
			"size": Vector2i(1, 1),
			"color": Color("d8e8a8"),
			"description_lines": ["Cleric focus", "Prepares prayers for one cast each floor", "Readies Turn Undead every door"],
			"tags": ["magical"],
			"hand_card": {
				"card_id": "turn_undead_card",
				"generation_mode": "door_interval",
				"door_interval": 1,
				"max_stored_cards": 1,
			},
		},
		"arcana_conduit": {
			"name": "Arcana Conduit",
			"short": "ACD",
			"item_level": 0,
			"size": Vector2i(1, 1),
			"color": Color("9fc6ff"),
			"description_lines": ["Wizard starter focus", "Level 0: unlimited uses", "Adds Reset Cooldowns"],
			"tags": ["magical"],
			"hand_card": {
				"card_id": "arcane_reset_card",
				"generation_mode": "single",
				"initial_queued_cards": 1,
				"max_stored_cards": 1,
			},
		},
		"scroll_fireball": {
			"name": "Scroll of Fireball",
			"short": "SFB",
			"size": Vector2i(1, 2),
			"color": Color("ff9a5e"),
			"description_lines": ["Single-use spell scroll", "Cast once or study in calm as a wizard"],
			"tags": ["scroll", "magical"],
			"hand_card": {"card_id": "fireball_card", "generation_mode": "single", "phase_override": "any", "learnable_spell_scroll": true, "consume_item_on_play": true, "max_stored_cards": 1, "name_override": "Fireball Scroll", "description_lines_override": ["Cast Fireball once", "Wizard can study it in calm mode"]},
		},
		"scroll_magic_missile": {
			"name": "Scroll of Magic Missile",
			"short": "SMM",
			"size": Vector2i(1, 2),
			"color": Color("c18dff"),
			"description_lines": ["Single-use spell scroll", "Cast once or study in calm as a wizard"],
			"tags": ["scroll", "magical"],
			"hand_card": {"card_id": "magic_missile_card", "generation_mode": "single", "phase_override": "any", "learnable_spell_scroll": true, "consume_item_on_play": true, "max_stored_cards": 1, "name_override": "Magic Missile Scroll", "description_lines_override": ["Launch seeking missiles once", "Wizard can study it in calm mode"]},
		},
		"scroll_scorcher": {
			"name": "Scroll of Scorcher",
			"short": "SSC",
			"size": Vector2i(1, 2),
			"color": Color("ff9b63"),
			"description_lines": ["Single-use spell scroll", "Cast once or study in calm as a wizard"],
			"tags": ["scroll", "magical"],
			"hand_card": {"card_id": "scorcher_card", "generation_mode": "single", "phase_override": "any", "learnable_spell_scroll": true, "consume_item_on_play": true, "max_stored_cards": 1, "name_override": "Scorcher Scroll", "description_lines_override": ["Channel flames in a cone", "Damage over time continues until interrupted", "The flame cone also hits allies"]},
		},
		"scroll_web": {
			"name": "Scroll of Web",
			"short": "SWB",
			"size": Vector2i(1, 2),
			"color": Color("c9f0ff"),
			"description_lines": ["Single-use spell scroll", "Cast once or study in calm as a wizard"],
			"tags": ["scroll", "magical"],
			"hand_card": {"card_id": "web_card", "generation_mode": "single", "phase_override": "any", "learnable_spell_scroll": true, "consume_item_on_play": true, "max_stored_cards": 1, "name_override": "Web Scroll", "description_lines_override": ["Root enemies in an area once", "Wizard can study it in calm mode"]},
		},
		"scroll_shield": {
			"name": "Scroll of Shield",
			"short": "SSH",
			"size": Vector2i(1, 2),
			"color": Color("9fc8ff"),
			"description_lines": ["Single-use spell scroll", "Cast once or study in calm as a wizard"],
			"tags": ["scroll", "magical"],
			"hand_card": {"card_id": "shield_card", "generation_mode": "single", "phase_override": "any", "learnable_spell_scroll": true, "consume_item_on_play": true, "max_stored_cards": 1, "name_override": "Shield Scroll", "description_lines_override": ["Gain a temporary arcane barrier", "Wizard can study it in calm mode"]},
		},
		"scroll_haste": {
			"name": "Scroll of Haste",
			"short": "SHS",
			"size": Vector2i(1, 2),
			"color": Color("ffd56e"),
			"description_lines": ["Single-use spell scroll", "Cast once or study in calm as a wizard"],
			"tags": ["scroll", "magical"],
			"hand_card": {"card_id": "haste_card", "generation_mode": "single", "phase_override": "any", "learnable_spell_scroll": true, "consume_item_on_play": true, "max_stored_cards": 1, "name_override": "Haste Scroll", "description_lines_override": ["Buff the highest-damage ally in a room", "Double move speed and attack speed for 18s"]},
		},
		"scroll_lightning_bolt": {
			"name": "Scroll of Lightning Bolt",
			"short": "SLB",
			"size": Vector2i(1, 2),
			"color": Color("8bd9ff"),
			"description_lines": ["Single-use spell scroll", "Cast once or study in calm as a wizard"],
			"tags": ["scroll", "magical"],
			"hand_card": {"card_id": "lightning_bolt_card", "generation_mode": "single", "phase_override": "any", "learnable_spell_scroll": true, "consume_item_on_play": true, "max_stored_cards": 1, "name_override": "Lightning Bolt Scroll", "description_lines_override": ["Fire a piercing line through a doorway", "Wizard can study it in calm mode"]},
		},
		"scroll_light_cantrip": {
			"name": "Scroll of Light",
			"short": "SLT",
			"size": Vector2i(1, 2),
			"color": Color("fff1a8"),
			"description_lines": ["Single-use spell scroll", "Cast once or study in calm as a wizard"],
			"tags": ["scroll", "magical"],
			"hand_card": {"card_id": "light_cantrip_card", "generation_mode": "single", "phase_override": "any", "learnable_spell_scroll": true, "consume_item_on_play": true, "max_stored_cards": 1, "name_override": "Light Scroll", "description_lines_override": ["Create wizard light once", "Wizard can study it in calm mode"]},
		},
		"scroll_scry": {
			"name": "Scroll of Scry",
			"short": "SCR",
			"size": Vector2i(1, 2),
			"color": Color("9ed7ff"),
			"description_lines": ["Single-use spell scroll", "Cast once or study in calm as a wizard"],
			"tags": ["scroll", "magical"],
			"hand_card": {"card_id": "scry_card", "generation_mode": "single", "phase_override": "any", "learnable_spell_scroll": true, "consume_item_on_play": true, "max_stored_cards": 1, "name_override": "Scry Scroll", "description_lines_override": ["Reveal adjacent sealed rooms once", "Wizard can study it in calm mode"]},
		},
		"scroll_find_familiar": {
			"name": "Scroll of Find Familiar",
			"short": "SFF",
			"size": Vector2i(1, 2),
			"color": Color("b8d1ff"),
			"description_lines": ["Single-use spell scroll", "Cast once or study in calm as a wizard"],
			"tags": ["scroll", "magical"],
			"hand_card": {"card_id": "find_familiar_card", "generation_mode": "single", "phase_override": "any", "learnable_spell_scroll": true, "consume_item_on_play": true, "max_stored_cards": 1, "name_override": "Find Familiar Scroll", "description_lines_override": ["Summon an allied familiar once", "Wizard can study it in calm mode"]},
		},
		"scroll_cure_light_wounds": {
			"name": "Scroll of Cure Light Wounds",
			"short": "SCW",
			"size": Vector2i(1, 2),
			"color": Color("c3ffb3"),
			"description_lines": ["Single-use prayer scroll", "Cast once or study in calm as a cleric"],
			"tags": ["scroll", "magical"],
			"hand_card": {"card_id": "cure_light_wounds_card", "generation_mode": "single", "phase_override": "any", "learnable_spell_scroll": true, "consume_item_on_play": true, "max_stored_cards": 1, "name_override": "Cure Light Wounds Scroll", "description_lines_override": ["Restore 50% max health once", "Auto-casts to save a fallen ally in the same room"]},
		},
		"scroll_sanctuary": {
			"name": "Scroll of Sanctuary",
			"short": "SSY",
			"size": Vector2i(1, 2),
			"color": Color("e3ff9f"),
			"description_lines": ["Single-use prayer scroll", "Cast once or study in calm as a cleric"],
			"tags": ["scroll", "magical"],
			"hand_card": {"card_id": "sanctuary_card", "generation_mode": "single", "phase_override": "any", "learnable_spell_scroll": true, "consume_item_on_play": true, "max_stored_cards": 1, "name_override": "Sanctuary Scroll", "description_lines_override": ["Bless the most wounded ally in one room once", "Cleric can study it in calm mode"]},
		},
		"scroll_hold_person": {
			"name": "Scroll of Hold Person",
			"short": "SHP",
			"size": Vector2i(1, 2),
			"color": Color("d9c0ff"),
			"description_lines": ["Single-use prayer scroll", "Cast once or study in calm as a cleric"],
			"tags": ["scroll", "magical"],
			"hand_card": {"card_id": "hold_person_card", "generation_mode": "single", "phase_override": "any", "learnable_spell_scroll": true, "consume_item_on_play": true, "max_stored_cards": 1, "name_override": "Hold Person Scroll", "description_lines_override": ["Paralyze one enemy once", "Melee attacks against that target are critical"]},
		},
		"scroll_fear": {
			"name": "Scroll of Fear",
			"short": "SFR",
			"size": Vector2i(1, 2),
			"color": Color("cda3ff"),
			"description_lines": ["Single-use prayer scroll", "Cast once or study in calm as a cleric"],
			"tags": ["scroll", "magical"],
			"hand_card": {"card_id": "fear_card", "generation_mode": "single", "phase_override": "any", "learnable_spell_scroll": true, "consume_item_on_play": true, "max_stored_cards": 1, "name_override": "Fear Scroll", "description_lines_override": ["Terrify enemies in a long cone for 6s", "Feared enemies flee and take 2x damage"]},
		},
		"scroll_calm_emotions": {
			"name": "Scroll of Calm Emotions",
			"short": "SCE",
			"size": Vector2i(1, 2),
			"color": Color("b7e8ff"),
			"description_lines": ["Single-use prayer scroll", "Cast once or study in calm as a cleric"],
			"tags": ["scroll", "magical"],
			"hand_card": {"card_id": "calm_emotions_card", "generation_mode": "single", "phase_override": "any", "learnable_spell_scroll": true, "consume_item_on_play": true, "max_stored_cards": 1, "name_override": "Calm Emotions Scroll", "description_lines_override": ["Pacify enemies in one opened room for 12s", "Effect ends early when enemies take damage"]},
		},
		"scroll_beacon_of_hope": {
			"name": "Scroll of Beacon of Hope",
			"short": "SBH",
			"size": Vector2i(1, 2),
			"color": Color("d4ff9f"),
			"description_lines": ["Single-use prayer scroll", "Cast once or study in calm as a cleric"],
			"tags": ["scroll", "magical"],
			"hand_card": {"card_id": "beacon_of_hope_card", "generation_mode": "single", "phase_override": "any", "learnable_spell_scroll": true, "consume_item_on_play": true, "max_stored_cards": 1, "name_override": "Beacon of Hope Scroll", "description_lines_override": ["Bless all allies in one room", "Adds mitigation and regeneration"]},
		},
		"scroll_spiritual_weapon": {
			"name": "Scroll of Spiritual Weapon",
			"short": "SSW",
			"size": Vector2i(1, 2),
			"color": Color("f0f1ff"),
			"description_lines": ["Single-use prayer scroll", "Cast once; clerics auto-prepare this prayer by level"],
			"tags": ["scroll", "magical"],
			"hand_card": {"card_id": "spiritual_weapon_card", "generation_mode": "single", "phase_override": "any", "learnable_spell_scroll": true, "consume_item_on_play": true, "max_stored_cards": 1, "name_override": "Spiritual Weapon Scroll", "description_lines_override": ["Summon an invulnerable spectral blade once", "No study required for clerics"]},
		},
		"scroll_animate_dead": {
			"name": "Scroll of Animate Dead",
			"short": "ADS",
			"size": Vector2i(1, 2),
			"color": Color("d0ffbe"),
			"description_lines": ["Single-use prayer scroll", "Cast once or study in calm as a cleric"],
			"tags": ["scroll", "magical"],
			"hand_card": {"card_id": "animate_dead_card", "generation_mode": "single", "phase_override": "any", "learnable_spell_scroll": true, "consume_item_on_play": true, "max_stored_cards": 1, "name_override": "Animate Dead Scroll", "description_lines_override": ["Summon three temporary skeleton allies", "Cleric prepares by level; wizard can study in calm mode"]},
		},
	}
	for item_id_variant in definitions.keys():
		var item_id: String = String(item_id_variant)
		definitions[item_id]["icon_path"] = "res://assets/generated/items/%s.png" % item_id
	return definitions
